const quotes = [
    "The best way to predict your future is to create it.",
    "You only live once, but if you do it right, once is enough.",
    "Life is really simple, but we insist on making it complicated.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "The purpose of our lives is to be happy.",
    "Get busy living or get busy dying.",
    "Life is short, and it's up to you to make it sweet.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Life is either a daring adventure or nothing at all.",
    "The only impossible journey is the one you never begin.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The best way out is always through.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "You must be the change you wish to see in the world.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Life is what happens when you're busy making other plans.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "We do not remember days; we remember moments.",
    "The only way to do great work is to love what you do.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with one step.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The only person you are destined to become is the person you decide to be.",
    "Act as if what you do makes a difference. It does.",
    "You are never too old to set another goal or to dream a new dream.",
    "Our lives begin to end the day we become silent about things that matter.",
    "You must do the things you think you cannot do.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The only way to have a friend is to be one.",
    "In order to succeed, we must first believe that we can.",
    "We may encounter many defeats but we must not be defeated.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Don’t judge each day by the harvest you reap but by the seeds that you plant.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "The harder I work, the luckier I get.",
    "Opportunities don't happen. You create them.",
    "Don't be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not in what you have, but who you are.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Your time is limited, don’t waste it living someone else’s life.",
    "If you want to lift yourself up, lift up someone else.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "It always seems impossible until it's done.",
    "The only way to achieve the impossible is to believe it is possible.",
    "The best revenge is massive success.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The only place where success comes before work is in the dictionary.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don’t let yesterday take up too much of today.",
    "You don’t have to be perfect to be amazing.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The best way to predict the future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Start where you are. Use what you have. Do what you can.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "If you want to achieve greatness stop asking for permission.",
    "You get what you give.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Believe it. Build it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work, the more it pays off.",
    "Dream it. Wish it. Do it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Success is not for the chosen few, but for the few who choose it.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Motivation gets you going and habit gets you there.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The best way to predict your future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You are never too old to set another goal or to dream a new dream.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only way to do great work is to love what you do.",
    "The only person you are destined to become is the person you decide to be.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You must be the change you wish to see in the world.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with one step.",
    "Success is not in what you have, but who you are.",
    "You only live once, but if you do it right, once is enough.",
    "Life is what happens when you're busy making other plans.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Act as if what you do makes a difference. It does.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only person you are destined to become is the person you decide to be.",
    "Start where you are. Use what you have. Do what you can.",
    "Dream it. Wish it. Do it.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only way to achieve the impossible is to believe it is possible.",
    "The best revenge is massive success.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The only place where success comes before work is in the dictionary.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don’t let yesterday take up too much of today.",
    "You don’t have to be perfect to be amazing.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The best way to predict the future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Start where you are. Use what you have. Do what you can.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "If you want to achieve greatness stop asking for permission.",
    "You get what you give.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Believe it. Build it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work, the more it pays off.",
    "Dream it. Wish it. Do it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Success is not for the chosen few, but for the few who choose it.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Motivation gets you going and habit gets you there.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The best way to predict your future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You are never too old to set another goal or to dream a new dream.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only way to do great work is to love what you do.",
    "The only person you are destined to become is the person you decide to be.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You must be the change you wish to see in the world.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with one step.",
    "Success is not in what you have, but who you are.",
    "You only live once, but if you do it right, once is enough.",
    "Life is what happens when you're busy making other plans.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Act as if what you do makes a difference. It does.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only person you are destined to become is the person you decide to be.",
    "Start where you are. Use what you have. Do what you can.",
    "Dream it. Wish it. Do it.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only way to achieve the impossible is to believe it is possible.",
    "The best revenge is massive success.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The only place where success comes before work is in the dictionary.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don’t let yesterday take up too much of today.",
    "You don’t have to be perfect to be amazing.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The best way to predict the future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Start where you are. Use what you have. Do what you can.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "If you want to achieve greatness stop asking for permission.",
    "You get what you give.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Believe it. Build it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work, the more it pays off.",
    "Dream it. Wish it. Do it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Success is not for the chosen few, but for the few who choose it.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Motivation gets you going and habit gets you there.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The best way to predict your future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You are never too old to set another goal or to dream a new dream.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only way to do great work is to love what you do.",
    "The only person you are destined to become is the person you decide to be.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You must be the change you wish to see in the world.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with one step.",
    "Success is not in what you have, but who you are.",
    "You only live once, but if you do it right, once is enough.",
    "Life is what happens when you're busy making other plans.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Act as if what you do makes a difference. It does.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only person you are destined to become is the person you decide to be.",
    "Start where you are. Use what you have. Do what you can.",
    "Dream it. Wish it. Do it.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only way to achieve the impossible is to believe it is possible.",
    "The best revenge is massive success.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The only place where success comes before work is in the dictionary.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don’t let yesterday take up too much of today.",
    "You don’t have to be perfect to be amazing.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The best way to predict the future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Start where you are. Use what you have. Do what you can.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "If you want to achieve greatness stop asking for permission.",
    "You get what you give.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Believe it. Build it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work, the more it pays off.",
    "Dream it. Wish it. Do it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Success is not for the chosen few, but for the few who choose it.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Motivation gets you going and habit gets you there.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The best way to predict your future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You are never too old to set another goal or to dream a new dream.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only way to do great work is to love what you do.",
    "The only person you are destined to become is the person you decide to be.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You must be the change you wish to see in the world.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with one step.",
    "Success is not in what you have, but who you are.",
    "You only live once, but if you do it right, once is enough.",
    "Life is what happens when you're busy making other plans.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Act as if what you do makes a difference. It does.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only person you are destined to become is the person you decide to be.",
    "Start where you are. Use what you have. Do what you can.",
    "Dream it. Wish it. Do it.",
    "Little things make big days. Great things are not done by impulse, but by a series of small things brought together.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The best preparation for tomorrow is doing your best today.",
    "The future depends on what you do today.",
    "The only way to achieve the impossible is to believe it is possible.",
    "The best revenge is massive success.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The only place where success comes before work is in the dictionary.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don’t let yesterday take up too much of today.",
    "You don’t have to be perfect to be amazing.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The best way to predict the future is to create it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Start where you are. Use what you have. Do what you can.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "If you want to achieve greatness stop asking for permission.",
    "You get what you give.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Believe it. Build it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work, the more it pays off.",
    "Dream it. Wish it. Do it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Wake up with determination. Go to bed with satisfaction."
];

function getDayOfYear(date) {
    const start = new Date(date.getFullYear(), 0, 0);
    const diff = date - start;
    const oneDay = 1000 * 60 * 60 * 24;
    return Math.floor(diff / oneDay) + 1;
}

function getDailyQuote() {
    const date = new Date();
    const dayOfYear = getDayOfYear(date);
    const index = (dayOfYear - 1) % quotes.length;
    return quotes[index];
}

document.getElementById('quote').innerText = getDailyQuote();